[WIP] restore multiplicities
p2l1pfp/cmssw pull request #9
Opened 2019-04-11 22:49 UTC by jmduarte

2019-04-12 07:15 UTC, gpetruc requested changes

2019-04-12 07:15 UTC, gpetruc commented on L1Trigger/Phase2L1ParticleFlow/plugins/L1TPFProducer.cc
> +
Remove the also the FIXME above

2019-06-18 16:18 UTC, jmduarte commented on L1Trigger/Phase2L1ParticleFlow/plugins/L1TPFProducer.cc
> +
Removed

2019-06-18 17:37 UTC, jmduarte commented
@gpetruc I updated the PR. Let me know if I should rebase and make it to another branch as well.

2019-06-20 09:49 UTC, gpetruc commented on L1Trigger/Phase2L1ParticleFlow/python/l1ParticleFlow_cff.py
> +    l1pfProducerHGCalNoTK
did you make some check that this makes no difference in the PF & Puppi output

2019-09-19 10:48 UTC, gpetruc commented
closing, now integrated in the 10_6_1p2 branch

2019-09-19 10:48 UTC, closed without merging